-- Creating the table for boxes
CREATE TABLE wordsbox (
    box_id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    box_title text NOT NULL,
    box_content text
);

-- Creating the exercise table
CREATE TABLE dragdrop (
    id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title text UNIQUE NOT NULL,
    box_id bigint,
    FOREIGN KEY (box_id) REFERENCES wordsbox(box_id)
);
