-- Create an anchors table to store anchor IDs
CREATE TABLE anchors (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  anchor_id TEXT NOT NULL UNIQUE
);

CREATE TRIGGER updated_at
BEFORE UPDATE
ON public.anchors
FOR EACH ROW
EXECUTE FUNCTION updated_at();

-- Create a linking table between exercises and anchors
CREATE TABLE exercise_anchors (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  exercise_id BIGINT NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  anchor_id BIGINT NOT NULL REFERENCES anchors(id) ON DELETE CASCADE,
  position INT NOT NULL DEFAULT 0,
  UNIQUE (exercise_id, anchor_id)
);

CREATE TRIGGER updated_at
BEFORE UPDATE
ON public.exercise_anchors
FOR EACH ROW
EXECUTE FUNCTION updated_at();

-- Create indexes for faster lookups
CREATE INDEX exercise_anchors_anchor_id_idx ON exercise_anchors(anchor_id);
CREATE INDEX exercise_anchors_exercise_id_idx ON exercise_anchors(exercise_id);

-- Add a category column to exercises table if it doesn't exist already
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'exercises' AND column_name = 'category') THEN
    ALTER TABLE exercises ADD COLUMN category TEXT;
  END IF;
END $$; 