CREATE TABLE grammar_pages_html (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    grammar_topic_id INTEGER REFERENCES grammar_topics(id)

);