BEGIN;

-- Memory game exercise metadata
CREATE TABLE IF NOT EXISTS memory_game_exercises (
  id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  exercise_id BIGINT NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  UNIQUE (exercise_id)
);

CREATE TRIGGER updated_at
  BEFORE UPDATE ON memory_game_exercises
  FOR EACH ROW EXECUTE FUNCTION updated_at();

-- Memory game pairs: one left item and one matching right item per pair.
CREATE TABLE IF NOT EXISTS memory_game_pairs (
  id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  memory_game_exercise_id BIGINT NOT NULL REFERENCES memory_game_exercises(id) ON DELETE CASCADE,
  left_item TEXT NOT NULL,
  right_item TEXT NOT NULL,
  pair_order INTEGER NOT NULL,
  UNIQUE (memory_game_exercise_id, pair_order),
  UNIQUE (memory_game_exercise_id, right_item)
);

CREATE TRIGGER updated_at
  BEFORE UPDATE ON memory_game_pairs
  FOR EACH ROW EXECUTE FUNCTION updated_at();

CREATE INDEX IF NOT EXISTS memory_game_pairs_exercise_order_idx
  ON memory_game_pairs (memory_game_exercise_id, pair_order);

-- Student answers for memory games.
CREATE TABLE IF NOT EXISTS memory_game_user_answers (
  id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  memory_game_exercise_id BIGINT NOT NULL REFERENCES memory_game_exercises(id) ON DELETE CASCADE,
  attempts JSONB NOT NULL,
  score INTEGER NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (user_id, memory_game_exercise_id)
);

CREATE TRIGGER updated_at
  BEFORE UPDATE ON memory_game_user_answers
  FOR EACH ROW EXECUTE FUNCTION updated_at();

CREATE INDEX IF NOT EXISTS memory_game_user_answers_user_exercise_idx
  ON memory_game_user_answers (user_id, memory_game_exercise_id);

COMMIT;
