-- Jumbled Sentence Exercises Table
CREATE TABLE public.jumbled_sentence_exercises (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  exercise_id bigint UNIQUE NOT NULL,
  created_by bigint NOT NULL,
  title text NOT NULL
);

ALTER TABLE public.jumbled_sentence_exercises
ADD CONSTRAINT jumbled_sentence_exercises_created_by_fkey
FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE public.jumbled_sentence_exercises
ADD CONSTRAINT jumbled_sentence_exercises_exercise_id_fkey
FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE;

CREATE TABLE public.jumbled_sentence_sentences (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  jumbled_exercise_id bigint NOT NULL,
  sentence text NOT NULL,
  alternates text[] DEFAULT ARRAY[]::text[],
  CONSTRAINT fk_jumbled_exercise FOREIGN KEY(jumbled_exercise_id) REFERENCES jumbled_sentence_exercises(id) ON DELETE CASCADE
);
