BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- Exercise metadata table
-- One row per exercise; links to the central exercises hub via exercise_id.
-- Both title and description are required (NOT NULL).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dnd_match_exercises (
  id                  BIGINT      PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  exercise_id         BIGINT      NOT NULL REFERENCES exercises(id)  ON DELETE CASCADE,
  created_by          BIGINT      NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
  title               TEXT        NOT NULL,
  description         TEXT        NOT NULL,
  UNIQUE (exercise_id)
);

CREATE TRIGGER updated_at
  BEFORE UPDATE ON dnd_match_exercises
  FOR EACH ROW EXECUTE FUNCTION updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- Ordered pairs table
-- Each row is one left↔right pairing.
-- pair_order drives the fixed left-column display sequence.
-- Uniqueness on (exercise_id, pair_order) guarantees a deterministic ordering.
-- Uniqueness on (exercise_id, right_item) prevents ambiguous right-side values.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dnd_match_pairs (
  id                      BIGINT      PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  dnd_match_exercise_id   BIGINT      NOT NULL REFERENCES dnd_match_exercises(id) ON DELETE CASCADE,
  left_item               TEXT        NOT NULL,
  right_item              TEXT        NOT NULL,
  pair_order              INTEGER     NOT NULL,
  UNIQUE (dnd_match_exercise_id, pair_order),
  UNIQUE (dnd_match_exercise_id, right_item)
);

CREATE TRIGGER updated_at
  BEFORE UPDATE ON dnd_match_pairs
  FOR EACH ROW EXECUTE FUNCTION updated_at();

CREATE INDEX IF NOT EXISTS dnd_match_pairs_exercise_order_idx
  ON dnd_match_pairs (dnd_match_exercise_id, pair_order);

-- ─────────────────────────────────────────────────────────────────────────────
-- User-answer table
-- Records which right_item a student placed against each left_item slot.
-- is_correct is evaluated server-side at submit time (not generated) so
-- it can be updated independently on retry via ON CONFLICT … DO UPDATE.
-- Uniqueness on (user_id, dnd_match_exercise_id, left_pair_id) means each
-- user has exactly one recorded choice per left slot; retry overwrites it.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dnd_match_user_answers (
  id                      BIGINT      PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id                 BIGINT      NOT NULL REFERENCES users(id)            ON DELETE CASCADE,
  dnd_match_exercise_id   BIGINT      NOT NULL REFERENCES dnd_match_exercises(id) ON DELETE CASCADE,
  left_pair_id            BIGINT      NOT NULL REFERENCES dnd_match_pairs(id)  ON DELETE CASCADE,
  selected_right_pair_id  BIGINT      NOT NULL REFERENCES dnd_match_pairs(id)  ON DELETE CASCADE,
  is_correct              BOOLEAN     NOT NULL DEFAULT false,
  UNIQUE (user_id, dnd_match_exercise_id, left_pair_id)
);

CREATE TRIGGER updated_at
  BEFORE UPDATE ON dnd_match_user_answers
  FOR EACH ROW EXECUTE FUNCTION updated_at();

CREATE INDEX IF NOT EXISTS dnd_match_user_answers_user_exercise_idx
  ON dnd_match_user_answers (user_id, dnd_match_exercise_id);

CREATE INDEX IF NOT EXISTS dnd_match_user_answers_exercise_idx
  ON dnd_match_user_answers (dnd_match_exercise_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Cross-exercise pair integrity trigger
-- Prevents a user answer from referencing pair IDs that belong to a different
-- exercise than the one recorded in dnd_match_exercise_id.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION check_dnd_match_pair_exercise_integrity()
  RETURNS trigger
  LANGUAGE plpgsql
AS $$
DECLARE
  left_exercise_id  BIGINT;
  right_exercise_id BIGINT;
BEGIN
  SELECT dnd_match_exercise_id INTO left_exercise_id
    FROM dnd_match_pairs WHERE id = NEW.left_pair_id;

  SELECT dnd_match_exercise_id INTO right_exercise_id
    FROM dnd_match_pairs WHERE id = NEW.selected_right_pair_id;

  IF left_exercise_id IS DISTINCT FROM NEW.dnd_match_exercise_id
     OR right_exercise_id IS DISTINCT FROM NEW.dnd_match_exercise_id THEN
    RAISE EXCEPTION
      'dnd_match_user_answers: left_pair_id and selected_right_pair_id must belong to dnd_match_exercise_id %',
      NEW.dnd_match_exercise_id;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER check_pair_exercise_integrity
  BEFORE INSERT OR UPDATE ON dnd_match_user_answers
  FOR EACH ROW EXECUTE FUNCTION check_dnd_match_pair_exercise_integrity();

COMMIT;
