CREATE TABLE public.click_false_word_feedbacks (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  click_exercise_id bigint NOT NULL REFERENCES click_exercises(id) ON DELETE CASCADE,
  slot_key text NOT NULL,
  word_text text NOT NULL,
  feedback text NOT NULL,
  CONSTRAINT click_false_word_feedbacks_unique UNIQUE (click_exercise_id, slot_key)
);

CREATE TRIGGER updated_at
BEFORE UPDATE ON public.click_false_word_feedbacks
FOR EACH ROW
EXECUTE FUNCTION updated_at();