CREATE OR REPLACE FUNCTION public.updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
	BEGIN
		NEW.updated_at = NOW();
		RETURN NEW;
	END;
$function$
;

CREATE TABLE public.form_parts (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  form_id bigint NOT NULL,
  title_en text,
  title_de text,
  step_label text NOT NULL
);

ALTER TABLE public.form_parts
ADD CONSTRAINT check_step_label
CHECK ((step_label ~ '^[A-Za-z0-9]$'::text));

ALTER TABLE public.form_parts
ADD CONSTRAINT unique_step_label
UNIQUE (form_id, step_label);

CREATE TRIGGER updated_at BEFORE UPDATE ON public.form_parts FOR EACH ROW EXECUTE FUNCTION updated_at();

CREATE TABLE public.forms (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  public_id text UNIQUE NOT NULL,
  title_en text,
  title_de text,
  description_en text,
  description_de text
);

CREATE TRIGGER updated_at BEFORE UPDATE ON public.forms FOR EACH ROW EXECUTE FUNCTION updated_at();

ALTER TABLE public.form_parts
ADD CONSTRAINT form_parts_form_id_fkey
FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE RESTRICT;

CREATE TABLE public.part_questions (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  form_part_id bigint NOT NULL,
  title_en text,
  title_de text
);

CREATE TRIGGER updated_at BEFORE UPDATE ON public.part_questions FOR EACH ROW EXECUTE FUNCTION updated_at();

ALTER TABLE public.part_questions
ADD CONSTRAINT part_questions_form_part_id_fkey
FOREIGN KEY (form_part_id) REFERENCES form_parts(id) ON DELETE RESTRICT;

CREATE TABLE public.pgmigrate_migrations (
  id text PRIMARY KEY NOT NULL,
  checksum text NOT NULL,
  execution_time_in_millis bigint NOT NULL,
  applied_at timestamp with time zone NOT NULL
);

CREATE SEQUENCE public.user_form_answers_id_seq;

CREATE TABLE public.user_form_answers (
  id integer PRIMARY KEY NOT NULL DEFAULT nextval('user_form_answers_id_seq'::regclass),
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  user_id integer NOT NULL,
  form_id integer NOT NULL,
  answer integer NOT NULL
);

CREATE UNIQUE INDEX user_form_answers_user_id_form_id_idx ON public.user_form_answers USING btree (user_id, form_id);

CREATE TRIGGER updated_at BEFORE UPDATE ON public.user_form_answers FOR EACH ROW EXECUTE FUNCTION updated_at();

ALTER SEQUENCE public.user_form_answers_id_seq OWNED BY public.user_form_answers.id;

ALTER TABLE public.user_form_answers
ADD CONSTRAINT user_form_answers_form_id_fkey
FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE;

CREATE TABLE public.users (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TRIGGER updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION updated_at();

ALTER TABLE public.user_form_answers
ADD CONSTRAINT user_form_answers_user_id_fkey
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE SEQUENCE public.user_part_answers_id_seq;

CREATE TABLE public.user_part_answers (
  id integer PRIMARY KEY NOT NULL DEFAULT nextval('user_part_answers_id_seq'::regclass),
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  user_id integer NOT NULL,
  form_part_id integer NOT NULL,
  answer integer NOT NULL
);

CREATE UNIQUE INDEX user_part_answers_user_id_form_part_id_idx ON public.user_part_answers USING btree (user_id, form_part_id);

CREATE TRIGGER updated_at BEFORE UPDATE ON public.user_part_answers FOR EACH ROW EXECUTE FUNCTION updated_at();

ALTER SEQUENCE public.user_part_answers_id_seq OWNED BY public.user_part_answers.id;

ALTER TABLE public.user_part_answers
ADD CONSTRAINT user_part_answers_form_part_id_fkey
FOREIGN KEY (form_part_id) REFERENCES form_parts(id) ON DELETE CASCADE;

ALTER TABLE public.user_part_answers
ADD CONSTRAINT user_part_answers_user_id_fkey
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE TABLE public.user_question_answers (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  answer integer NOT NULL,
  user_id bigint NOT NULL,
  part_question_id bigint NOT NULL
);

ALTER TABLE public.user_question_answers
ADD CONSTRAINT user_question_answers_user_id_part_question_id_key
UNIQUE (user_id, part_question_id);

CREATE TRIGGER updated_at BEFORE UPDATE ON public.user_question_answers FOR EACH ROW EXECUTE FUNCTION updated_at();

ALTER TABLE public.user_question_answers
ADD CONSTRAINT user_question_answers_part_question_id_fkey
FOREIGN KEY (part_question_id) REFERENCES part_questions(id) ON DELETE RESTRICT;

ALTER TABLE public.user_question_answers
ADD CONSTRAINT user_question_answers_user_id_fkey
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
