--
-- PostgreSQL database dump
--

\restrict Gr1h4q03HXltmjJKAKR7g44rdCEJeTtcfMFC8Wg1ht1eAXNaDCOq4QAf9JJJRao

-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 17.8 (Debian 17.8-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: insert_into_exercises(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.insert_into_exercises() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    new_exercise_id BIGINT;
BEGIN
    -- Insert a new row into the exercises table
    INSERT INTO exercises (created_at, updated_at, category)
    VALUES (NOW(), NOW(), 'click')
    RETURNING id INTO new_exercise_id;

    -- Link the new exercise to the click_exercises entry
    INSERT INTO click_to_exercises (click_id, exercise_id, created_at, updated_at)
    VALUES (NEW.id, new_exercise_id, NOW(), NOW());

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.insert_into_exercises() OWNER TO postgres;

--
-- Name: updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
	BEGIN
		NEW.updated_at = NOW();
		RETURN NEW;
	END;
$$;


ALTER FUNCTION public.updated_at() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: anchors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.anchors (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    anchor_id text NOT NULL
);


ALTER TABLE public.anchors OWNER TO postgres;

--
-- Name: anchors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.anchors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anchors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: click_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.click_answers (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id bigint NOT NULL,
    click_exercise_id bigint NOT NULL,
    answer text[] NOT NULL,
    target_words text[] NOT NULL,
    is_correct boolean GENERATED ALWAYS AS ((answer = target_words)) STORED NOT NULL
);


ALTER TABLE public.click_answers OWNER TO postgres;

--
-- Name: click_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.click_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.click_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: click_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.click_exercises (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    category text NOT NULL,
    target_words text[] NOT NULL,
    all_words text[] NOT NULL
);


ALTER TABLE public.click_exercises OWNER TO postgres;

--
-- Name: click_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.click_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.click_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: click_to_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.click_to_exercises (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    click_id bigint,
    exercise_id bigint
);


ALTER TABLE public.click_to_exercises OWNER TO postgres;

--
-- Name: click_to_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.click_to_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.click_to_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dnd_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dnd_categories (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    category text NOT NULL,
    color text NOT NULL
);


ALTER TABLE public.dnd_categories OWNER TO postgres;

--
-- Name: dnd_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dnd_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dnd_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dnd_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dnd_exercises (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by bigint NOT NULL,
    exercise_id bigint NOT NULL,
    title text NOT NULL
);


ALTER TABLE public.dnd_exercises OWNER TO postgres;

--
-- Name: dnd_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dnd_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dnd_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dnd_user_answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dnd_user_answer (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id bigint NOT NULL,
    word_id bigint NOT NULL,
    category_id bigint,
    is_correct boolean NOT NULL
);


ALTER TABLE public.dnd_user_answer OWNER TO postgres;

--
-- Name: dnd_user_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dnd_user_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dnd_user_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: draggable_words; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.draggable_words (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    word text NOT NULL
);


ALTER TABLE public.draggable_words OWNER TO postgres;

--
-- Name: draggable_words_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.draggable_words ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.draggable_words_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercise_anchors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise_anchors (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    exercise_id bigint NOT NULL,
    anchor_id bigint NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    difficulty text DEFAULT 'medium'::text NOT NULL,
    title text,
    CONSTRAINT exercise_anchors_difficulty_check CHECK ((difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])))
);


ALTER TABLE public.exercise_anchors OWNER TO postgres;

--
-- Name: exercise_anchors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercise_anchors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_anchors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercises (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    category text,
    created_by bigint
);


ALTER TABLE public.exercises OWNER TO postgres;

--
-- Name: exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercises_to_grammar_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercises_to_grammar_items (
    id bigint NOT NULL,
    grammar_item_id bigint,
    exercise_id bigint
);


ALTER TABLE public.exercises_to_grammar_items OWNER TO postgres;

--
-- Name: exercises_to_grammar_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercises_to_grammar_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_to_grammar_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedbacks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feedbacks (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    message text NOT NULL,
    user_id integer NOT NULL,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.feedbacks OWNER TO postgres;

--
-- Name: feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.feedbacks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.feedbacks_id_seq OWNER TO postgres;

--
-- Name: feedbacks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.feedbacks_id_seq OWNED BY public.feedbacks.id;


--
-- Name: form_parts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.form_parts (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    form_id bigint NOT NULL,
    title_en text,
    title_de text,
    step_label text NOT NULL,
    advice_en text,
    advice_de text,
    advice_threshold numeric(5,2) DEFAULT 3,
    CONSTRAINT check_step_label CHECK ((step_label ~ '^[A-Za-z0-9]$'::text))
);


ALTER TABLE public.form_parts OWNER TO postgres;

--
-- Name: form_parts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.form_parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    public_id text NOT NULL,
    title_en text,
    title_de text,
    description_en text,
    description_de text
);


ALTER TABLE public.forms OWNER TO postgres;

--
-- Name: forms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: free_form_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.free_form_answers (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    free_form_exercise_id bigint NOT NULL,
    answer text NOT NULL,
    is_correct boolean DEFAULT false,
    feedback text
);


ALTER TABLE public.free_form_answers OWNER TO postgres;

--
-- Name: free_form_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.free_form_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.free_form_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: free_form_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.free_form_exercises (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    exercise_id bigint NOT NULL,
    question text NOT NULL
);


ALTER TABLE public.free_form_exercises OWNER TO postgres;

--
-- Name: free_form_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.free_form_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.free_form_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: free_form_user_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.free_form_user_answers (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    answer text NOT NULL,
    free_form_exercise_id bigint NOT NULL,
    is_correct boolean DEFAULT false,
    user_id bigint NOT NULL
);


ALTER TABLE public.free_form_user_answers OWNER TO postgres;

--
-- Name: free_form_user_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.free_form_user_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.free_form_user_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: glossary_entries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.glossary_entries (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    word text NOT NULL,
    word_definition text NOT NULL
);


ALTER TABLE public.glossary_entries OWNER TO postgres;

--
-- Name: glossary_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.glossary_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.glossary_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grammar_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grammar_items (
    id bigint NOT NULL,
    grammar_item text NOT NULL
);


ALTER TABLE public.grammar_items OWNER TO postgres;

--
-- Name: grammar_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.grammar_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grammar_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: html_pages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.html_pages (
    id bigint NOT NULL,
    title text,
    content text,
    page_order integer,
    slug text,
    page_group text
);


ALTER TABLE public.html_pages OWNER TO postgres;

--
-- Name: html_pages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.html_pages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.html_pages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multichoice_content; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multichoice_content (
    id bigint NOT NULL,
    multichoice_exercise_id bigint NOT NULL,
    content_type text NOT NULL,
    content_value text NOT NULL,
    content_order integer NOT NULL,
    correct_answer text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.multichoice_content OWNER TO postgres;

--
-- Name: multichoice_content_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.multichoice_content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multichoice_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multichoice_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multichoice_exercises (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    title text NOT NULL,
    exercise_description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.multichoice_exercises OWNER TO postgres;

--
-- Name: multichoice_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.multichoice_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multichoice_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multichoice_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multichoice_options (
    id bigint NOT NULL,
    multichoice_content_id bigint NOT NULL,
    option_value text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.multichoice_options OWNER TO postgres;

--
-- Name: multichoice_options_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.multichoice_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multichoice_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: part_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.part_questions (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    form_part_id bigint NOT NULL,
    title_en text,
    title_de text
);


ALTER TABLE public.part_questions OWNER TO postgres;

--
-- Name: part_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.part_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.part_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pgmigrate_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pgmigrate_migrations (
    id text NOT NULL,
    checksum text NOT NULL,
    execution_time_in_millis bigint NOT NULL,
    applied_at timestamp with time zone NOT NULL
);


ALTER TABLE public.pgmigrate_migrations OWNER TO postgres;

--
-- Name: user_question_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_question_answers (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    answer integer NOT NULL,
    user_id bigint,
    part_question_id bigint NOT NULL,
    answerer_id text NOT NULL
);


ALTER TABLE public.user_question_answers OWNER TO postgres;

--
-- Name: user_question_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_question_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_question_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    salt text NOT NULL,
    username text DEFAULT ''::text NOT NULL,
    is_admin boolean DEFAULT false,
    is_superadmin boolean DEFAULT false NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: word_category_mappings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.word_category_mappings (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    word_id bigint NOT NULL,
    category_id bigint NOT NULL,
    exercise_id bigint NOT NULL
);


ALTER TABLE public.word_category_mappings OWNER TO postgres;

--
-- Name: word_category_mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.word_category_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.word_category_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedbacks id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedbacks ALTER COLUMN id SET DEFAULT nextval('public.feedbacks_id_seq'::regclass);


--
-- Name: anchors anchors_anchor_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.anchors
    ADD CONSTRAINT anchors_anchor_id_key UNIQUE (anchor_id);


--
-- Name: anchors anchors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.anchors
    ADD CONSTRAINT anchors_pkey PRIMARY KEY (id);


--
-- Name: click_answers click_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_answers
    ADD CONSTRAINT click_answers_pkey PRIMARY KEY (id);


--
-- Name: click_answers click_answers_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_answers
    ADD CONSTRAINT click_answers_unique UNIQUE (user_id, click_exercise_id);


--
-- Name: click_exercises click_exercises_all_words_target_words_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_exercises
    ADD CONSTRAINT click_exercises_all_words_target_words_key UNIQUE (all_words, target_words);


--
-- Name: click_exercises click_exercises_id_target_words_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_exercises
    ADD CONSTRAINT click_exercises_id_target_words_key UNIQUE (id, target_words);


--
-- Name: click_exercises click_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_exercises
    ADD CONSTRAINT click_exercises_pkey PRIMARY KEY (id);


--
-- Name: click_to_exercises click_to_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_to_exercises
    ADD CONSTRAINT click_to_exercises_pkey PRIMARY KEY (id);


--
-- Name: dnd_categories dnd_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_categories
    ADD CONSTRAINT dnd_categories_pkey PRIMARY KEY (id);


--
-- Name: dnd_exercises dnd_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_exercises
    ADD CONSTRAINT dnd_exercises_pkey PRIMARY KEY (id);


--
-- Name: dnd_user_answer dnd_user_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_user_answer
    ADD CONSTRAINT dnd_user_answer_pkey PRIMARY KEY (id);


--
-- Name: draggable_words draggable_words_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.draggable_words
    ADD CONSTRAINT draggable_words_pkey PRIMARY KEY (id);


--
-- Name: exercise_anchors exercise_anchors_exercise_id_anchor_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_anchors
    ADD CONSTRAINT exercise_anchors_exercise_id_anchor_id_key UNIQUE (exercise_id, anchor_id);


--
-- Name: exercise_anchors exercise_anchors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_anchors
    ADD CONSTRAINT exercise_anchors_pkey PRIMARY KEY (id);


--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);


--
-- Name: exercises_to_grammar_items exercises_to_grammar_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises_to_grammar_items
    ADD CONSTRAINT exercises_to_grammar_items_pkey PRIMARY KEY (id);


--
-- Name: feedbacks feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT feedbacks_pkey PRIMARY KEY (id);


--
-- Name: form_parts form_parts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.form_parts
    ADD CONSTRAINT form_parts_pkey PRIMARY KEY (id);


--
-- Name: forms forms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms
    ADD CONSTRAINT forms_pkey PRIMARY KEY (id);


--
-- Name: free_form_answers free_form_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_answers
    ADD CONSTRAINT free_form_answers_pkey PRIMARY KEY (id);


--
-- Name: free_form_exercises free_form_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_exercises
    ADD CONSTRAINT free_form_exercises_pkey PRIMARY KEY (id);


--
-- Name: free_form_user_answers free_form_user_answers_free_form_exercise_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_user_answers
    ADD CONSTRAINT free_form_user_answers_free_form_exercise_id_user_id_key UNIQUE (free_form_exercise_id, user_id);


--
-- Name: free_form_user_answers free_form_user_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_user_answers
    ADD CONSTRAINT free_form_user_answers_pkey PRIMARY KEY (id);


--
-- Name: glossary_entries glossary_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.glossary_entries
    ADD CONSTRAINT glossary_entries_pkey PRIMARY KEY (id);


--
-- Name: grammar_items grammar_items_grammar_item_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grammar_items
    ADD CONSTRAINT grammar_items_grammar_item_key UNIQUE (grammar_item);


--
-- Name: grammar_items grammar_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grammar_items
    ADD CONSTRAINT grammar_items_pkey PRIMARY KEY (id);


--
-- Name: html_pages html_pages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.html_pages
    ADD CONSTRAINT html_pages_pkey PRIMARY KEY (id);


--
-- Name: multichoice_content multichoice_content_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multichoice_content
    ADD CONSTRAINT multichoice_content_pkey PRIMARY KEY (id);


--
-- Name: multichoice_exercises multichoice_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multichoice_exercises
    ADD CONSTRAINT multichoice_exercises_pkey PRIMARY KEY (id);


--
-- Name: multichoice_options multichoice_options_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multichoice_options
    ADD CONSTRAINT multichoice_options_pkey PRIMARY KEY (id);


--
-- Name: part_questions part_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.part_questions
    ADD CONSTRAINT part_questions_pkey PRIMARY KEY (id);


--
-- Name: pgmigrate_migrations pgmigrate_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pgmigrate_migrations
    ADD CONSTRAINT pgmigrate_migrations_pkey PRIMARY KEY (id);


--
-- Name: dnd_categories unique_category_color; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_categories
    ADD CONSTRAINT unique_category_color UNIQUE (category, color);


--
-- Name: forms unique_public_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms
    ADD CONSTRAINT unique_public_id UNIQUE (public_id);


--
-- Name: form_parts unique_step_label; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.form_parts
    ADD CONSTRAINT unique_step_label UNIQUE (form_id, step_label);


--
-- Name: draggable_words unique_word; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.draggable_words
    ADD CONSTRAINT unique_word UNIQUE (word);


--
-- Name: user_question_answers user_question_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_question_answers
    ADD CONSTRAINT user_question_answers_pkey PRIMARY KEY (id);


--
-- Name: user_question_answers user_question_answers_user_id_part_question_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_question_answers
    ADD CONSTRAINT user_question_answers_user_id_part_question_id_key UNIQUE (user_id, part_question_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: word_category_mappings word_category_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.word_category_mappings
    ADD CONSTRAINT word_category_mappings_pkey PRIMARY KEY (id);


--
-- Name: exercise_anchors_anchor_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exercise_anchors_anchor_id_idx ON public.exercise_anchors USING btree (anchor_id);


--
-- Name: exercise_anchors_exercise_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exercise_anchors_exercise_id_idx ON public.exercise_anchors USING btree (exercise_id);


--
-- Name: free_form_answers_free_form_exercise_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX free_form_answers_free_form_exercise_id_idx ON public.free_form_answers USING btree (free_form_exercise_id);


--
-- Name: click_exercises after_click_exercises_insert; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER after_click_exercises_insert AFTER INSERT ON public.click_exercises FOR EACH ROW EXECUTE FUNCTION public.insert_into_exercises();


--
-- Name: glossary_entries update_glossary_entries_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_glossary_entries_updated_at BEFORE UPDATE ON public.glossary_entries FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: anchors updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.anchors FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: click_answers updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.click_answers FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: click_exercises updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.click_exercises FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: click_to_exercises updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.click_to_exercises FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: dnd_categories updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.dnd_categories FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: dnd_exercises updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.dnd_exercises FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: dnd_user_answer updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.dnd_user_answer FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: draggable_words updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.draggable_words FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: exercise_anchors updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.exercise_anchors FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: exercises updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.exercises FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: form_parts updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.form_parts FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: forms updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.forms FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: free_form_answers updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.free_form_answers FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: free_form_exercises updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.free_form_exercises FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: free_form_user_answers updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.free_form_user_answers FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: multichoice_content updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.multichoice_content FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: multichoice_exercises updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.multichoice_exercises FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: multichoice_options updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.multichoice_options FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: part_questions updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.part_questions FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: user_question_answers updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.user_question_answers FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: users updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: word_category_mappings updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updated_at BEFORE UPDATE ON public.word_category_mappings FOR EACH ROW EXECUTE FUNCTION public.updated_at();


--
-- Name: click_answers click_answers_click_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_answers
    ADD CONSTRAINT click_answers_click_exercise_id_fkey FOREIGN KEY (click_exercise_id) REFERENCES public.click_exercises(id) ON DELETE CASCADE;


--
-- Name: click_answers click_answers_click_exercise_id_target_words_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_answers
    ADD CONSTRAINT click_answers_click_exercise_id_target_words_fkey FOREIGN KEY (click_exercise_id, target_words) REFERENCES public.click_exercises(id, target_words) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: click_answers click_answers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_answers
    ADD CONSTRAINT click_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: click_to_exercises click_to_exercises_click_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_to_exercises
    ADD CONSTRAINT click_to_exercises_click_id_fkey FOREIGN KEY (click_id) REFERENCES public.click_exercises(id);


--
-- Name: click_to_exercises click_to_exercises_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.click_to_exercises
    ADD CONSTRAINT click_to_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id);


--
-- Name: dnd_exercises dnd_exercises_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_exercises
    ADD CONSTRAINT dnd_exercises_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: dnd_exercises dnd_exercises_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_exercises
    ADD CONSTRAINT dnd_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id) ON DELETE CASCADE;


--
-- Name: dnd_user_answer dnd_user_answer_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_user_answer
    ADD CONSTRAINT dnd_user_answer_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.dnd_categories(id) ON DELETE CASCADE;


--
-- Name: dnd_user_answer dnd_user_answer_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_user_answer
    ADD CONSTRAINT dnd_user_answer_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: dnd_user_answer dnd_user_answer_word_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dnd_user_answer
    ADD CONSTRAINT dnd_user_answer_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.draggable_words(id) ON DELETE CASCADE;


--
-- Name: exercise_anchors exercise_anchors_anchor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_anchors
    ADD CONSTRAINT exercise_anchors_anchor_id_fkey FOREIGN KEY (anchor_id) REFERENCES public.anchors(id) ON DELETE CASCADE;


--
-- Name: exercise_anchors exercise_anchors_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_anchors
    ADD CONSTRAINT exercise_anchors_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id) ON DELETE CASCADE;


--
-- Name: exercises exercises_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: exercises_to_grammar_items exercises_to_grammar_items_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises_to_grammar_items
    ADD CONSTRAINT exercises_to_grammar_items_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id);


--
-- Name: exercises_to_grammar_items exercises_to_grammar_items_grammar_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises_to_grammar_items
    ADD CONSTRAINT exercises_to_grammar_items_grammar_item_id_fkey FOREIGN KEY (grammar_item_id) REFERENCES public.grammar_items(id);


--
-- Name: form_parts form_parts_form_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.form_parts
    ADD CONSTRAINT form_parts_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id) ON DELETE RESTRICT;


--
-- Name: free_form_answers free_form_answers_free_form_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_answers
    ADD CONSTRAINT free_form_answers_free_form_exercise_id_fkey FOREIGN KEY (free_form_exercise_id) REFERENCES public.free_form_exercises(id) ON DELETE CASCADE;


--
-- Name: free_form_exercises free_form_exercises_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_exercises
    ADD CONSTRAINT free_form_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id) ON DELETE CASCADE;


--
-- Name: free_form_user_answers free_form_user_answers_free_form_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_user_answers
    ADD CONSTRAINT free_form_user_answers_free_form_exercise_id_fkey FOREIGN KEY (free_form_exercise_id) REFERENCES public.free_form_exercises(id) ON DELETE CASCADE;


--
-- Name: free_form_user_answers free_form_user_answers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.free_form_user_answers
    ADD CONSTRAINT free_form_user_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: multichoice_content multichoice_content_multichoice_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multichoice_content
    ADD CONSTRAINT multichoice_content_multichoice_exercise_id_fkey FOREIGN KEY (multichoice_exercise_id) REFERENCES public.multichoice_exercises(id) ON DELETE CASCADE;


--
-- Name: multichoice_exercises multichoice_exercises_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multichoice_exercises
    ADD CONSTRAINT multichoice_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id) ON DELETE CASCADE;


--
-- Name: multichoice_options multichoice_options_multichoice_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multichoice_options
    ADD CONSTRAINT multichoice_options_multichoice_content_id_fkey FOREIGN KEY (multichoice_content_id) REFERENCES public.multichoice_content(id) ON DELETE CASCADE;


--
-- Name: part_questions part_questions_form_part_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.part_questions
    ADD CONSTRAINT part_questions_form_part_id_fkey FOREIGN KEY (form_part_id) REFERENCES public.form_parts(id) ON DELETE RESTRICT;


--
-- Name: user_question_answers user_question_answers_part_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_question_answers
    ADD CONSTRAINT user_question_answers_part_question_id_fkey FOREIGN KEY (part_question_id) REFERENCES public.part_questions(id) ON DELETE RESTRICT;


--
-- Name: user_question_answers user_question_answers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_question_answers
    ADD CONSTRAINT user_question_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: word_category_mappings word_category_mappings_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.word_category_mappings
    ADD CONSTRAINT word_category_mappings_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.dnd_categories(id) ON DELETE CASCADE;


--
-- Name: word_category_mappings word_category_mappings_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.word_category_mappings
    ADD CONSTRAINT word_category_mappings_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.dnd_exercises(id) ON DELETE CASCADE;


--
-- Name: word_category_mappings word_category_mappings_word_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.word_category_mappings
    ADD CONSTRAINT word_category_mappings_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.draggable_words(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict Gr1h4q03HXltmjJKAKR7g44rdCEJeTtcfMFC8Wg1ht1eAXNaDCOq4QAf9JJJRao

